"""Model-driven variant of the demo agent, generated by llama.cpp on CPU.

The scripted trace in ``agent.py`` is deterministic: it always finds the deep
bug because the steps are hard-coded.  This module hands the same job to the
*actual* SFT'd small model served by ``llama-server`` and verifies every SQL it
emits against the real trap / clean databases, so what the UI shows is what the
model genuinely produced — including when it is wrong.

Honest caveat, worth reading before judging the output: the checkpoint in
``checkpoints/sft-0.5b/`` was trained on the ``ciclos_calibrados`` single-table
defect catalog (``vendor/defect_catalog.py``), **not** on this bespoke 8-table
pipeline.  Running it here is deliberately out-of-distribution — it is a
stress test of generalisation, not a reproduction of the 0.70 held-out number.
Use ``scripts/eval_cpu.sh`` for the in-distribution measurement.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from typing import Iterator

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))

from deep_debug_run import (FIELD_DEPENDENCIES, TABLES, build_clean, build_trap,
                            grade, transitive_deps)

SYS_PROMPT = (
    "You are a senior SAS/IRB data-quality debugger. A credit-risk pipeline "
    "produces the table t8_final (and its source tables t1..t7) from a deep "
    "multi-layer SAS program. A regulator flagged a set of recovery cycles as "
    "suspicious. You are given the schema, the pipeline lineage, and ONE "
    "suspected cycle. Decide whether the cycle's values are incoherent, and if "
    "so localise the root cause. Respond ONLY with a JSON object containing "
    "these keys:\n"
    '  "diagnostic_sql": the SQL that, run on the whole pipeline, flags every '
    "row with the same incoherence (select the cycle id first, do NOT filter by "
    "cycle id),\n"
    '  "root_cause": {"table", "columns", "transformation", "reason"}, and\n'
    '  "extraction_request": an optional read-only SELECT extracting the key '
    "fields needed to confirm (empty string if not needed)."
)


def schema_text() -> str:
    lines = ["SCHEMA (SQLite, 8 tables)"]
    for t, cols in TABLES.items():
        lines.append(f"  {t}({', '.join(cols)})")
    return "\n".join(lines)


def lineage_text() -> str:
    lines = ["FIELD LINEAGE (field <- inputs)"]
    for field, deps in FIELD_DEPENDENCIES.items():
        lines.append(f"  {field} <- {', '.join(deps) if deps else '(source)'}")
    return "\n".join(lines)


def build_user_prompt(suspect: dict, suspect_id: str) -> str:
    row = " | ".join(f"{k}={v}" for k, v in suspect.items())
    return (
        f"{schema_text()}\n\n{lineage_text()}\n\n"
        f"SUSPECTED CYCLE\n"
        f"  cycle_id = {suspect_id}\n"
        f"  reported values (table t8_final):\n  {row}\n\n"
        f"TASK\n"
        f"  Determine what is wrong with this cycle and where the discrepancy "
        f"comes from.\n"
        f"  Print the diagnostic SQL and the root-cause localisation (table, "
        f"columns,\n  transformation, reason) as JSON."
    )


def exec_named(conn, sql: str):
    """Run a read-only SELECT and return (status, rows, column_names)."""
    try:
        cur = conn.execute(sql)
        rows = cur.fetchall()
        cols = [d[0] for d in (cur.description or [])]
        return "rows", rows, cols
    except Exception as e:  # the model writes the SQL; it can be invalid
        return "err", str(e), []


def parse_json(text: str) -> dict | None:
    m = re.search(r"\{.*\}", text or "", re.DOTALL)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except json.JSONDecodeError:
        return None


def run_model_agent(egp_src: str, egp_rep: str, xlsx_path: str, *,
                    llama_url: str | None = None, attempts: int = 4,
                    temperature: float = 0.7) -> Iterator[dict]:
    """Yield the same event kinds as ``agent.run_agent``, model-generated.

    ``attempts`` samples are drawn (the first greedy, the rest at
    ``temperature``) and each one's SQL is graded against the real DBs; the
    first attempt that catches the planted cycle with no false positives wins.
    This is the demo-shaped version of the best-of-N selection in
    ``slm.evaluate``.
    """
    from slm.backends import LlamaCppBackend, DEFAULT_LLAMA_URL
    from agent import _egp_lineage, _load_xlsx_rows, _sleep

    url = llama_url or os.environ.get("LLAMA_SERVER_URL", DEFAULT_LLAMA_URL)
    backend = LlamaCppBackend(url)
    ok, detail = backend.health()
    yield {"kind": "backend", "backend": "llamacpp", "url": url,
           "healthy": ok, "detail": detail}
    if not ok:
        yield {"kind": "error",
               "text": (f"llama-server is not reachable ({detail}). Start it with "
                        f"`bash scripts/llama_server.sh`, or reload the page in "
                        f"scripted mode.")}
        return

    src = _egp_lineage(egp_src)
    rep = _egp_lineage(egp_rep)
    cycles = _load_xlsx_rows(xlsx_path)

    clean = build_clean(1500, 7)
    trap, dirty_pk = build_trap(1500, 7, 3)
    try:
        flagged = next((c for c in cycles if str(c.get("FLAG", "")) == "DUDA"), None)
        suspect_id = flagged.get("ID_CICLO") if flagged else dirty_pk
        row = trap.execute("SELECT * FROM t8_final WHERE ID_CICLO=?",
                           (suspect_id,)).fetchone()
        if row is None:
            suspect_id = dirty_pk
            row = trap.execute("SELECT * FROM t8_final WHERE ID_CICLO=?",
                               (suspect_id,)).fetchone()
        suspect = dict(zip(TABLES["t8_final"], row))

        yield {"kind": "header", "source_project": src.get("name"),
               "report_project": rep.get("name"),
               "source_tables": src.get("tables_produced"),
               "report_tables": rep.get("tables_produced"),
               "suspects": len(cycles), "suspect_id": suspect_id}
        _sleep(0.2)

        deps = transitive_deps("ECL", FIELD_DEPENDENCIES)
        yield {"kind": "reason",
               "text": (f"Asking the SFT'd 0.5B (llama.cpp, CPU) to debug cycle "
                        f"`{suspect_id}`: reported `ECL` = {suspect['ECL']:.4f}, "
                        f"which depends transitively on {len(deps)} fields across "
                        f"7 tables. Every query it emits is executed against the "
                        f"real trap and clean databases — nothing below is "
                        f"scripted.")}

        user = build_user_prompt(suspect, suspect_id)
        best = None
        for i in range(max(1, attempts)):
            greedy = (i == 0)
            t0 = time.time()
            try:
                raw = backend.generate(SYS_PROMPT, user, do_sample=not greedy,
                                       temperature=temperature,
                                       max_new_tokens=384)
            except Exception as e:
                yield {"kind": "error", "text": f"llama-server error: {e}"}
                return
            dt = time.time() - t0
            parsed = parse_json(raw)
            if parsed is None:
                yield {"kind": "reason",
                       "text": (f"Attempt {i+1}/{attempts} "
                                f"({'greedy' if greedy else f'temp {temperature}'}, "
                                f"{dt:.1f}s): the model did not return parseable "
                                f"JSON. Resampling.")}
                continue

            diag = (parsed.get("diagnostic_sql") or "").strip()
            extraction = (parsed.get("extraction_request") or "").strip()
            root_cause = parsed.get("root_cause") or {}

            if extraction:
                st, rows, cols = exec_named(trap, extraction)
                yield {"kind": "extract", "sql": extraction,
                       "table": (root_cause.get("table") or "?"),
                       "rows": (dict(zip(cols, rows[0])) if st == "rows" and rows
                                else None),
                       "note": (f"Model-requested extraction — "
                                f"{'ran, ' + str(len(rows)) + ' rows' if st == 'rows' else 'FAILED: ' + str(rows)}")}
                _sleep(0.2)

            verdict = grade(clean, trap, suspect_id, diag) if diag else {
                "valid": False, "caught": False, "false_positive": False,
                "trap_rows": None, "clean_rows": None,
                "error": "no diagnostic_sql emitted"}
            yield {"kind": "sql", "sql": diag, "verdict": verdict}
            yield {"kind": "reason",
                   "text": (f"Attempt {i+1}/{attempts} "
                            f"({'greedy' if greedy else f'temp {temperature}'}, "
                            f"{dt:.1f}s) — oracle verdict on the real DBs: "
                            f"valid={verdict['valid']}, caught={verdict['caught']}, "
                            f"false_positive={verdict['false_positive']}.")}
            _sleep(0.2)

            success = verdict["valid"] and verdict["caught"] and not verdict["false_positive"]
            if best is None or success:
                best = {"parsed": parsed, "verdict": verdict, "attempt": i + 1,
                        "success": success}
            if success:
                break

        if best is None:
            yield {"kind": "error",
                   "text": (f"The model produced no parseable JSON in {attempts} "
                            f"attempts. This 0.5B checkpoint was trained on the "
                            f"single-table `ciclos_calibrados` catalog, not on this "
                            f"8-table pipeline — see CPU_LLAMACPP.md.")}
            return

        rc = best["parsed"].get("root_cause") or {}
        yield {"kind": "localize", "root_cause": {
            "table": rc.get("table") or "(not localised)",
            "columns": rc.get("columns") or [],
            "transformation": rc.get("transformation") or "",
            "reason": rc.get("reason") or "",
        }}
        _sleep(0.3)

        if best["success"]:
            summary = (f"Model localised the discrepancy to `{rc.get('table')}` on "
                       f"attempt {best['attempt']}/{attempts}; its diagnostic SQL "
                       f"catches the flagged cycle with zero false positives on the "
                       f"clean database.")
        else:
            summary = (f"Model answered on attempt {best['attempt']}/{attempts} but "
                       f"the oracle rejected it (valid={best['verdict']['valid']}, "
                       f"caught={best['verdict']['caught']}, "
                       f"false_positive={best['verdict']['false_positive']}). The "
                       f"ground truth is `t7_ead_cal.EAD_FUERA` (built from "
                       f"`OR_DISPTO` instead of `OR_DISBLE`). This checkpoint was "
                       f"trained on a different schema — run the scripted trace to "
                       f"see the intended agent pass.")
        yield {"kind": "done", "summary": summary}
    finally:
        clean.close()
        trap.close()
